# name: Daily Readme Update

# on:
#   schedule:
#     - cron: '0 4,8,12,17,22 * * *'
# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Update readme
#         run: |
#           echo "peep " >> readme.md

#           git config --global user.email "xevenbiswas@gmail.com"
#           git config --global user.name "Anish"
#           git add readme.md
#           git commit -m "Added daily message to README on $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
#           git push origin main